phone-number-configuration:
  phoneNumbersConfigurations:
    -
      phoneRegex: "\\(237\\)\\ ?[2368]\\d{7,8}$"
      countryName: "Cameroon"
      code: "237"
      phoneNumbersStatesConfigurations: [ ]
    -
      phoneRegex: "\\(251\\)\\ ?[1-59]\\d{8}$"
      countryName: "Ethiopia"
      code: "251"
      phoneNumbersStatesConfigurations:
        -
          stateRegex: "\\(251\\)\\ ?9{1}[1]{2}\\d{6}$"
          stateName: "Addis Ababa"
          stateCode: "911"
        -
          stateRegex: "\\(251\\)\\ ?9{1}1{1}4{1}\\d{6}$"
          stateName: "Northern region"
          stateCode: "914"
        -
          stateRegex: "\\(251\\)\\ ?9{1}1{1}5{1}\\d{6}$"
          stateName: "East region"
          stateCode: "915"
        -
          stateRegex: "\\(251\\)\\ ?9{1}1{1}6{1}\\d{6}$"
          stateName: "Southern region"
          stateCode: "916"
        -
          stateRegex: "\\(251\\)\\ ?9{1}1{1}7{1}\\d{6}$"
          stateName: "Western region"
          stateCode: "917"
        -
          stateRegex: "\\(251\\)\\ ?9{1}1{1}8{1}\\d{6}$"
          stateName: "Northwestern region"
          stateCode: "918"
    -
      phoneRegex: "\\(212\\)\\ ?[5-9]\\d{8}$"
      countryName: "Morocco"
      code: "212"
      phoneNumbersStatesConfigurations: [ ]
    -
      phoneRegex: "\\(258\\)\\ ?[28]\\d{7,8}$"
      countryName: "Mozambique"
      code: "258"
      phoneNumbersStatesConfigurations: [ ]
    -
      phoneRegex: "\\(256\\)\\ ?\\d{9}$"
      countryName: "Uganda"
      code: "256"
      phoneNumbersStatesConfigurations: [ ]